---
version: "2"
services:
  sqlserver:
    build:
      context: ./apps/db
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: ./apps/db
        target: /db-src
    ports:
      - 1433:1433
    environment:
      MSSQL_AGENT_ENABLED: "true"
      MSSQL_PID: Standard
      SA_PASSWORD: P@ssw0rd1
      ACCEPT_EULA: "Y"

  api:
    build:
      context: ./apps/api
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: ./apps/api
        target: /api-src
    ports:
      - 8080:8080
      - 5000:5000
    command: sleep infinity
